name:  Learning GHA Concepts
on: [push]
jobs:
    practice:
        runs-on: macos-latest
        steps:
            - name: homebrew package update
              run: brew update 
            - name: git installation
              run: brew install git 

    duplicate:
        needs: practice
        runs-on: macos-latest
        steps:
            - name: homebrew package update
              run: brew update 
            - name: tree installation
              run: brew install tree 
              