name:  Learning GHA Concepts
on: [push,pull_request,issues]
jobs:
    practice:
        runs-on: macos-latest
        steps:
            - name: homebrew package update
              run: brew update 
            - name: git installation
              run: brew install git 

    duplicate:
        needs: practice
        runs-on: ubuntu-latest
        steps:
            - name:  package update
              run: sudo apt update -y
            - name: tree installation
              run: sudo apt install tree -y
    applicant:
        needs: practice
        runs-on: windows-latest
        steps:
            - name: windows i dont know
              run: echo "windows"
            - name: windows i don't know
              run: echo "windows"         